apiVersion: v2
name: countly-kafka
description: Kafka for Countly event streaming via Strimzi Operator
type: application
version: 0.1.0
appVersion: "4.2.0"
home: https://countly.com
icon: https://count.ly/images/logos/countly-logo.svg
sources:
  - https://github.com/Countly/countly-server
keywords:
  - kafka
  - streaming
  - countly
maintainers:
  - name: Countly
    url: https://countly.com
