{{- if (include "obs.deployPrometheus" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "obs.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "obs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
{{- end }}
