apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "countly.fullname" . }}-config-frontend
  labels:
    {{- include "countly.labels" . | nindent 4 }}
data:
  NODE_OPTIONS: {{ .Values.nodeOptions.frontend | quote }}
  {{- range $key, $value := .Values.config.frontend }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
