apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "countly.fullname" . }}-config-otel
  labels:
    {{- include "countly.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.otel }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
