{{- if .Values.global.imagePullSecretExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "global.imagePullSecrets[0].name is required when global.imagePullSecretExternalSecret.enabled is true" (include "countly.imagePullSecretName" .) }}
  labels:
    {{- include "countly.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.global.imagePullSecretExternalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ required "global.imagePullSecretExternalSecret.secretStoreRef.name is required when global.imagePullSecretExternalSecret.enabled is true" .Values.global.imagePullSecretExternalSecret.secretStoreRef.name }}
    kind: {{ .Values.global.imagePullSecretExternalSecret.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ required "global.imagePullSecrets[0].name is required when global.imagePullSecretExternalSecret.enabled is true" (include "countly.imagePullSecretName" .) }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ required "global.imagePullSecretExternalSecret.remoteRef.key is required when global.imagePullSecretExternalSecret.enabled is true" .Values.global.imagePullSecretExternalSecret.remoteRef.key }}
{{- end }}
