{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "countly.fullname" . }}-default-deny
  labels:
    {{- include "countly.labels" . | nindent 4 }}
  {{- if ((.Values.argocd).enabled) }}
  annotations:
    {{- include "countly.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "countly.fullname" . }}-allow-ingress
  labels:
    {{- include "countly.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "countly.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    # Allow traffic between Countly pods
    - from:
        - podSelector:
            matchLabels:
              {{- include "countly.selectorLabels" . | nindent 14 }}
    # Allow ingress controller traffic to frontend, api, ingestor, jobserver
    - from:
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
      ports:
        - port: {{ .Values.api.port }}
          protocol: TCP
        - port: {{ .Values.frontend.port }}
          protocol: TCP
        - port: {{ .Values.ingestor.port }}
          protocol: TCP
        - port: {{ .Values.jobserver.port }}
          protocol: TCP
    {{- if .Values.networkPolicy.additionalIngress }}
    {{- toYaml .Values.networkPolicy.additionalIngress | nindent 4 }}
    {{- end }}
{{- end }}
