{{- if not .Values.secrets.kafka.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "countly.fullname" . }}-kafka
  labels:
    {{- include "countly.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.secrets.keep }}
    helm.sh/resource-policy: keep
    {{- end }}
    {{- if .Values.secrets.rotationId }}
    countly.io/rotation-id: {{ .Values.secrets.rotationId | quote }}
    {{- end }}
type: Opaque
data:
  COUNTLY_CONFIG__KAFKA_RDKAFKA_BROKERS: {{ include "countly.kafka.brokers" . | b64enc }}
  COUNTLY_CONFIG__KAFKA_RDKAFKA_SECURITYPROTOCOL: {{ .Values.secrets.kafka.securityProtocol | b64enc }}
  {{- if .Values.secrets.kafka.saslMechanism }}
  COUNTLY_CONFIG__KAFKA_RDKAFKA_SASLMECHANISM: {{ .Values.secrets.kafka.saslMechanism | b64enc }}
  COUNTLY_CONFIG__KAFKA_RDKAFKA_SASLUSERNAME: {{ .Values.secrets.kafka.saslUsername | b64enc }}
  COUNTLY_CONFIG__KAFKA_RDKAFKA_SASLPASSWORD: {{ .Values.secrets.kafka.saslPassword | b64enc }}
  {{- end }}
{{- end }}
