{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "countly.serviceAccountName" . }}
  labels:
    {{- include "countly.labels" . | nindent 4 }}
  {{- if or .Values.argocd.enabled .Values.serviceAccount.annotations }}
  annotations:
    {{- include "countly.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
