{{- if (include "obs.deployGrafana" .) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obs.fullname" . }}-grafana-datasources
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- if .Values.metrics.enabled }}
    # Prometheus – metrics datasource
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: {{ include "obs.prometheus.url" . }}
      isDefault: true
    {{- end }}
    {{- if .Values.logs.enabled }}
    # Loki – logs datasource
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: {{ include "obs.loki.url" . }}
      {{- if .Values.traces.enabled }}
      jsonData:
        derivedFields:
          - name: traceID
            matcherRegex: 'traceId=([A-Fa-f0-9]{32})'
            url: ${__value.raw}
            datasourceUid: tempo
      {{- end }}
    {{- end }}
    {{- if .Values.traces.enabled }}
    # Tempo – traces datasource
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: {{ include "obs.tempo.httpUrl" . }}
      jsonData:
        httpMethod: GET
    {{- end }}
    {{- if .Values.profiling.enabled }}
    # Pyroscope – profiling datasource
    - name: Pyroscope
      uid: pyroscope
      type: grafana-pyroscope-datasource
      access: proxy
      url: {{ include "obs.pyroscope.url" . }}
    {{- end }}
{{- end }}
