{{- if and (include "obs.deployGrafana" .) (not .Values.grafana.admin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obs.fullname" . }}-grafana
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.grafana.admin.userKey }}: {{ "admin" | b64enc | quote }}
  {{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-grafana" (include "obs.fullname" .)) }}
  {{- if and $existing $existing.data (index $existing.data .Values.grafana.admin.passwordKey) }}
  {{ .Values.grafana.admin.passwordKey }}: {{ index $existing.data .Values.grafana.admin.passwordKey }}
  {{- else }}
  {{ .Values.grafana.admin.passwordKey }}: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
{{- end }}
