{{- if and .Values.exporter.enabled .Values.exporter.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "countly-mongodb.fullname" . }}-metrics
  labels:
    {{- include "countly-mongodb.labels" . | nindent 4 }}
    countly.io/metrics: "true"
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-mongodb.syncWave" (dict "wave" "10" "root" .) | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "countly-mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
  ports:
    - name: http-metrics
      port: {{ .Values.exporter.port }}
      targetPort: metrics
  type: ClusterIP
{{- end }}
