apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-letsencrypt-prod-issuer
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/helm.git
        revision: gcp-artifact-rep-integration
        files:
          - path: argocd/customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-letsencrypt-prod-issuer"
      annotations:
        argocd.argoproj.io/sync-wave: "-24"
    spec:
      project: default
      source:
        repoURL: https://github.com/Countly/helm.git
        targetRevision: gcp-artifact-rep-integration
        path: argocd/operator-manifests/letsencrypt-prod-issuer
        directory:
          recurse: true
      destination:
        server: "{{ .server }}"
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
