apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-prod-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-24"
spec:
  project: default
  source:
    repoURL: https://github.com/Countly/helm.git
    targetRevision: deploy-test-ui
    path: argocd/operator-manifests/letsencrypt-prod-issuer
    directory:
      recurse: true
  destination:
    server: https://34.135.156.216
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
