{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "countly-migrations.fullname" . }}-metrics
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
data:
  kafka-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: "kafka.server<type=BrokerTopicMetrics, name=(.+), topic=(.+)><>Count"
        name: "kafka_brokertopic_$1_total"
        labels:
          topic: "$2"
        type: COUNTER

  connect-metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      # Worker metrics
      - pattern: "kafka.connect<type=connect-worker-metrics>([^:]+):"
        name: "kafka_connect_worker_$1"
      - pattern: "kafka.connect<type=connect-worker-rebalance-metrics>([^:]+):"
        name: "kafka_connect_worker_rebalance_$1"
      # Connector-level metrics
      - pattern: "kafka.connect<type=connector-metrics, connector=(.+)><>(connector-class|connector-type|connector-version|status): (.+)"
        name: "kafka_connect_connector_$2"
        value: 1
        labels:
          connector: "$1"
          $2: "$3"
        type: UNTYPED
      # Task-level metrics
      - pattern: "kafka.connect<type=connector-task-metrics, connector=(.+), task=(\\d+)><>(.+): (.+)"
        name: "kafka_connect_task_$3"
        labels:
          connector: "$1"
          task: "$2"
      # Source task metrics
      - pattern: "kafka.connect<type=source-task-metrics, connector=(.+), task=(\\d+)><>(.+): (.+)"
        name: "kafka_connect_source_task_$3"
        labels:
          connector: "$1"
          task: "$2"
      # Sink task metrics
      - pattern: "kafka.connect<type=sink-task-metrics, connector=(.+), task=(\\d+)><>(.+): (.+)"
        name: "kafka_connect_sink_task_$3"
        labels:
          connector: "$1"
          task: "$2"
      # Fallback
      - pattern: "kafka.connect<type=(.+)><>([^:]+)"
        name: "kafka_connect_$1_$2"
{{- end }}
