{{- if .Values.connectors.clickhouseSink.enabled }}
apiVersion: {{ .Values.strimzi.apiVersion }}
kind: KafkaConnector
metadata:
  name: ch-sink-drill-migration-mig
  labels:
    strimzi.io/cluster: {{ include "countly-migrations.connectSinkName" . }}
    {{- include "countly-migrations.labels" . | nindent 4 }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "15" "root" .) | nindent 4 }}
spec:
  class: com.clickhouse.kafka.connect.ClickHouseSinkConnector
  tasksMax: {{ .Values.connectors.clickhouseSink.tasksMax }}
  state: {{ include "countly-migrations.connectorState" (dict "connector" .Values.connectors.clickhouseSink "global" .Values.migration) }}
  autoRestart:
    enabled: true
  config:
    topics: {{ .Values.connectors.clickhouseSink.topics | quote }}
    topic2TableMap: {{ .Values.connectors.clickhouseSink.topic2TableMap | quote }}

    hostname: "${env:CLICKHOUSE_HOST}"
    port: "${env:CLICKHOUSE_PORT}"
    ssl: "${env:CLICKHOUSE_SSL}"
    database: "${env:CLICKHOUSE_DB}"
    username: "${env:CLICKHOUSE_USER}"
    password: "${env:CLICKHOUSE_PASSWORD}"

    exactlyOnce: "${env:EXACTLY_ONCE}"
    errors.retry.timeout: "${env:ERRORS_RETRY_TIMEOUT}"
    errors.tolerance: "${env:ERRORS_TOLERANCE}"

    clickhouseSettings: "${env:CLICKHOUSE_SETTINGS}"
    bypassRowBinary: "${env:BYPASS_ROW_BINARY}"
    tableRefreshInterval: "${env:TABLE_REFRESH_INTERVAL}"

    key.converter: "${env:KEY_CONVERTER}"
    value.converter: "${env:VALUE_CONVERTER}"
    value.converter.schemas.enable: "${env:VALUE_CONVERTER_SCHEMAS_ENABLE}"

    consumer.override.fetch.min.bytes: "${env:KAFKA_CONSUMER_FETCH_MIN_BYTES}"
    consumer.override.fetch.max.wait.ms: "${env:KAFKA_CONSUMER_FETCH_MAX_WAIT_MS}"
    consumer.override.max.poll.records: "${env:KAFKA_CONSUMER_MAX_POLL_RECORDS}"
    consumer.override.max.partition.fetch.bytes: "${env:KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES}"
    consumer.override.fetch.max.bytes: "${env:KAFKA_CONSUMER_FETCH_MAX_BYTES}"

    {{- with .Values.connectors.clickhouseSink.dlq }}
    errors.deadletterqueue.topic.name: {{ .topicName | quote }}
    errors.deadletterqueue.topic.replication.factor: {{ .replicationFactor | quote }}
    errors.deadletterqueue.context.headers.enable: {{ .headerEnabled | quote }}
    {{- end }}
{{- end }}
