apiVersion: {{ .Values.strimzi.apiVersion }}
kind: KafkaConnect
metadata:
  name: {{ include "countly-migrations.connectSrcName" . }}
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  annotations:
    strimzi.io/use-connector-resources: "true"
    {{- include "countly-migrations.syncWave" (dict "wave" "10" "root" .) | nindent 4 }}
spec:
  version: {{ .Values.version | quote }}
  replicas: {{ .Values.connectSrc.replicas }}
  bootstrapServers: {{ include "countly-migrations.bootstrapServers" . }}
  image: {{ .Values.connectSrc.image }}
  {{- if .Values.metrics.enabled }}
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: {{ include "countly-migrations.fullname" . }}-metrics
        key: connect-metrics-config.yml
  {{- end }}
  resources:
    {{- toYaml .Values.connectSrc.resources | nindent 4 }}
  jvmOptions:
    -Xms: {{ .Values.connectSrc.jvmOptions.xms }}
    -Xmx: {{ .Values.connectSrc.jvmOptions.xmx }}
    javaSystemProperties:
      - name: com.sun.management.jmxremote
        value: "true"
      - name: com.sun.management.jmxremote.port
        value: "9999"
      - name: com.sun.management.jmxremote.authenticate
        value: "false"
      - name: com.sun.management.jmxremote.ssl
        value: "false"
  config:
    {{- range $key, $value := .Values.connectSrc.workerConfig }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    connectContainer:
      env:
        - name: DBZ_SNAPSHOT_MODE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_SNAPSHOT_MODE
        - name: DBZ_SNAPSHOT_MAX_THREADS
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_SNAPSHOT_MAX_THREADS
        - name: DBZ_SNAPSHOT_FETCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_SNAPSHOT_FETCH_SIZE
        - name: DBZ_MAX_BATCH_SIZE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_MAX_BATCH_SIZE
        - name: DBZ_MAX_QUEUE_SIZE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_MAX_QUEUE_SIZE
        - name: MONGO_CONN_STR
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: MONGO_CONN_STR
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: MONGO_DB
        - name: DBZ_FILTERS_MATCH_MODE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DBZ_FILTERS_MATCH_MODE
        - name: DRILL_EVENTS_NS_SELECTOR
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: DRILL_EVENTS_NS_SELECTOR
        - name: TOPIC_PREFIX
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: TOPIC_PREFIX
        - name: KEY_CONVERTER
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: KEY_CONVERTER
        - name: VALUE_CONVERTER
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: VALUE_CONVERTER
        - name: VALUE_CONVERTER_SCHEMAS_ENABLE
          valueFrom:
            configMapKeyRef:
              name: {{ include "countly-migrations.fullname" . }}-connect-env
              key: VALUE_CONVERTER_SCHEMAS_ENABLE
