{{- if not .Values.clickhouse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clickhouse.secretName }}
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if or .Values.secrets.keep .Values.argocd.enabled }}
  annotations:
    {{- if .Values.secrets.keep }}
    "helm.sh/resource-policy": keep
    {{- end }}
    {{- include "countly-migrations.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  username: {{ .Values.clickhouse.username | b64enc | quote }}
  password: {{ .Values.clickhouse.password | b64enc | quote }}
{{- end }}
