{{- if .Values.storageClass.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "-3" "root" .) | nindent 4 }}
  {{- end }}
provisioner: {{ .Values.storageClass.provisioner }}
{{- with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageClass.volumeBindingMode }}
{{- end }}
