apiVersion: v2
name: countly-mongodb
description: MongoDB for Countly via MongoDB Community Operator
type: application
version: 0.1.0
appVersion: "8.2.5"
home: https://countly.com
icon: https://count.ly/images/logos/countly-logo.svg
sources:
  - https://github.com/Countly/countly-server
keywords:
  - mongodb
  - database
  - countly
maintainers:
  - name: Countly
    url: https://countly.com
annotations:
  artifacthub.io/license: AGPL-3.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/Countly/helm
