{{- if .Values.progressMonitor.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "countly-migrations.fullname" . }}-progress
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "20" "root" .) | nindent 4 }}
  {{- end }}
{{- end }}
