{{- if (include "obs.deployLoki" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "obs.fullname" . }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "obs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: loki
  ports:
  - name: http
    port: 3100
    targetPort: 3100
    protocol: TCP
  - name: grpc
    port: 9096
    targetPort: 9096
    protocol: TCP
{{- end }}
