apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customer-strimzi-kafka-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/countly-deployment.git
        revision: main
        files:
          - path: customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-strimzi-kafka-operator"
      annotations:
        argocd.argoproj.io/sync-wave: "-26"
    spec:
      project: default
      source:
        repoURL: https://strimzi.io/charts/
        chart: strimzi-kafka-operator
        targetRevision: 0.51.0
        helm:
          releaseName: strimzi-kafka-operator
      destination:
        server: "{{ .server }}"
        namespace: kafka
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
