apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: countly-mongodb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/countly-deployment.git
        revision: countly-hosted-argo-layout
        files:
          - path: customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-mongodb"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: "{{ .project }}"
      sources:
        - repoURL: https://github.com/Countly/helm.git
          targetRevision: mutli-source-values-split
          path: charts/countly-mongodb
          helm:
            releaseName: countly-mongodb
            valueFiles:
              - "../../profiles/sizing/{{ .sizing }}/mongodb.yaml"
              - "../../profiles/security/{{ .security }}/mongodb.yaml"
              - "$values/environments/{{ .environment }}/global.yaml"
              - "$values/environments/{{ .environment }}/mongodb.yaml"
              - "$values/environments/{{ .environment }}/credentials-mongodb.yaml"
            parameters:
              - name: argocd.enabled
                value: "true"
              - name: global.sizing
                value: "{{ .sizing }}"
              - name: global.security
                value: "{{ .security }}"
        - repoURL: https://github.com/Countly/countly-deployment.git
          targetRevision: countly-hosted-argo-layout
          ref: values
      destination:
        server: "{{ .server }}"
        namespace: mongodb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: mongodbcommunity.mongodb.com
          kind: MongoDBCommunity
          jsonPointers:
            - /status
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[]?.remoteRef.conversionStrategy
            - .spec.data[]?.remoteRef.decodingStrategy
            - .spec.data[]?.remoteRef.metadataPolicy
