{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "countly-migration.fullname" . }}
  labels:
    {{- include "countly-migration.labels" . | nindent 4 }}
  {{- if ((.Values.argocd).enabled) }}
  annotations:
    {{- include "countly-migration.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "countly-migration.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- with .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.networkPolicy.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
