apiVersion: v2
name: countly
description: Countly web analytics platform - application deployments
type: application
version: 0.1.0
appVersion: "26.01"
home: https://countly.com
icon: https://count.ly/images/logos/countly-logo.svg
sources:
  - https://github.com/Countly/countly-server
keywords:
  - analytics
  - web-analytics
  - mobile-analytics
  - countly
maintainers:
  - name: Countly
    url: https://countly.com
