apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obs.fullname" . }}-prometheus
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  {{- if ((.Values.argocd).enabled) }}
  annotations:
    {{- include "obs.syncWave" (dict "wave" "0" "root" .) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
