apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obs.fullname" . }}-prometheus
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
automountServiceAccountToken: false
