{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: strimzi-cluster-operator-leader-election
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "-1" "root" .) | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: strimzi-cluster-operator
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: strimzi-cluster-operator-leader-election
{{- end }}
