{{- if .Values.operator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: strimzi-cluster-operator-leader-election
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "-1" "root" .) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
