{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: strimzi-cluster-operator
  labels:
    {{- include "countly-migrations.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-migrations.syncWave" (dict "wave" "-1" "root" .) | nindent 4 }}
  {{- end }}
{{- end }}
