{{- if .Values.kafka.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "countly-argocd.fullname" . }}-kafka
  namespace: argocd
  labels:
    {{- include "countly-argocd.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ include "countly-argocd.projectName" . }}
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: charts/countly-kafka
    helm:
      releaseName: countly-kafka
      valueFiles:
        - ../../environments/{{ .Values.environment }}/global.yaml
        - ../../profiles/sizing/{{ .Values.global.sizing }}/kafka.yaml
        - ../../profiles/kafka-connect/{{ .Values.global.kafkaConnect }}/kafka.yaml
        - ../../profiles/observability/{{ .Values.global.observability }}/kafka.yaml
        - ../../profiles/security/{{ .Values.global.security }}/kafka.yaml
        - ../../environments/{{ .Values.environment }}/kafka.yaml
        - ../../environments/{{ .Values.environment }}/secrets-kafka.yaml
      parameters:
        - name: argocd.enabled
          value: "true"
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.kafka.namespace }}
  {{- include "countly-argocd.syncPolicy" . | nindent 2 }}
  ignoreDifferences:
    - group: kafka.strimzi.io
      kind: Kafka
      jsonPointers:
        - /status
    - group: kafka.strimzi.io
      kind: KafkaConnect
      jsonPointers:
        - /status
    - group: kafka.strimzi.io
      kind: KafkaConnector
      jsonPointers:
        - /status
    - group: kafka.strimzi.io
      kind: KafkaNodePool
      jsonPointers:
        - /status
{{- end }}
