apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    gcpsm:
      projectID: {{ required "secretStore.secretManagerProjectID is required" .Values.secretStore.secretManagerProjectID | quote }}
      auth:
        workloadIdentity:
          clusterProjectID: {{ required "secretStore.clusterProjectID is required" .Values.secretStore.clusterProjectID | quote }}
          clusterName: {{ required "secretStore.clusterName is required" .Values.secretStore.clusterName | quote }}
          clusterLocation: {{ required "secretStore.clusterLocation is required" .Values.secretStore.clusterLocation | quote }}
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccountRef.name | quote }}
            namespace: {{ .Values.secretStore.serviceAccountRef.namespace | quote }}
