apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: countly-mongodb
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/helm.git
        revision: deploy-test-ui
        files:
          - path: argocd/customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-mongodb"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://github.com/Countly/helm.git
        targetRevision: deploy-test-ui
        path: charts/countly-mongodb
        helm:
          releaseName: countly-mongodb
          valueFiles:
            - "../../environments/{{ .environment }}/global.yaml"
            - "../../profiles/sizing/{{ .sizing }}/mongodb.yaml"
            - "../../profiles/security/{{ .security }}/mongodb.yaml"
            - "../../environments/{{ .environment }}/mongodb.yaml"
            - "../../environments/{{ .environment }}/secrets-mongodb.yaml"
          parameters:
            - name: argocd.enabled
              value: "true"
      destination:
        server: "{{ .server }}"
        namespace: mongodb
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: mongodbcommunity.mongodb.com
          kind: MongoDBCommunity
          jsonPointers:
            - /status
