apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: countly-clickhouse
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/helm.git
        revision: gcp-artifact-rep-integration
        files:
          - path: argocd/customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-clickhouse"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://github.com/Countly/helm.git
        targetRevision: gcp-artifact-rep-integration
        path: charts/countly-clickhouse
        helm:
          releaseName: countly-clickhouse
          valueFiles:
            - "../../environments/{{ .environment }}/global.yaml"
            - "../../profiles/sizing/{{ .sizing }}/clickhouse.yaml"
            - "../../profiles/security/{{ .security }}/clickhouse.yaml"
            - "../../environments/{{ .environment }}/clickhouse.yaml"
            - "../../environments/{{ .environment }}/secrets-clickhouse.yaml"
          parameters:
            - name: argocd.enabled
              value: "true"
            - name: global.sizing
              value: "{{ .sizing }}"
            - name: global.security
              value: "{{ .security }}"
      destination:
        server: "{{ .server }}"
        namespace: clickhouse
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: clickhouse.com
          kind: ClickHouseCluster
          jsonPointers:
            - /status
        - group: clickhouse.com
          kind: KeeperCluster
          jsonPointers:
            - /status
            - /spec/containerTemplate/resources/requests/memory
            - /spec/containerTemplate/resources/limits/memory
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .spec.data[]?.remoteRef.conversionStrategy
            - .spec.data[]?.remoteRef.decodingStrategy
            - .spec.data[]?.remoteRef.metadataPolicy
