apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: countly-kafka
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - customer: helm-argocd
            project: helm-argocd
            server: https://34.135.156.216
            sizing: production
            security: open
            observability: full
            kafkaConnect: balanced
  template:
    metadata:
      name: "{{customer}}-kafka"
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: "{{project}}"
      source:
        repoURL: https://github.com/Countly/helm.git
        targetRevision: deploy-test-ui
        path: charts/countly-kafka
        helm:
          releaseName: countly-kafka
          valueFiles:
            - "../../environments/{{customer}}/global.yaml"
            - "../../profiles/sizing/{{sizing}}/kafka.yaml"
            - "../../profiles/kafka-connect/{{kafkaConnect}}/kafka.yaml"
            - "../../profiles/observability/{{observability}}/kafka.yaml"
            - "../../profiles/security/{{security}}/kafka.yaml"
            - "../../environments/{{customer}}/kafka.yaml"
            - "../../environments/{{customer}}/secrets-kafka.yaml"
          parameters:
            - name: argocd.enabled
              value: "true"
      destination:
        server: "{{server}}"
        namespace: kafka
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
      ignoreDifferences:
        - group: kafka.strimzi.io
          kind: Kafka
          jsonPointers:
            - /status
        - group: kafka.strimzi.io
          kind: KafkaConnect
          jsonPointers:
            - /status
        - group: kafka.strimzi.io
          kind: KafkaConnector
          jsonPointers:
            - /status
        - group: kafka.strimzi.io
          kind: KafkaNodePool
          jsonPointers:
            - /status
