apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: countly-observability
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/Countly/helm.git
        revision: obs-test
        files:
          - path: argocd/customers/*.yaml
  template:
    metadata:
      name: "{{ .customer }}-observability"
      annotations:
        argocd.argoproj.io/sync-wave: "15"
    spec:
      project: "{{ .project }}"
      source:
        repoURL: https://github.com/Countly/helm.git
        targetRevision: obs-test
        path: charts/countly-observability
        helm:
          releaseName: countly-observability
          valueFiles:
            - "../../environments/{{ .environment }}/global.yaml"
            - "../../profiles/sizing/{{ .sizing }}/observability.yaml"
            - "../../profiles/observability/{{ .observability }}/observability.yaml"
            - "../../profiles/security/{{ .security }}/observability.yaml"
            - "../../environments/{{ .environment }}/observability.yaml"
            - "../../environments/{{ .environment }}/secrets-observability.yaml"
          parameters:
            - name: argocd.enabled
              value: "true"
      destination:
        server: "{{ .server }}"
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
