{{- if (include "obs.deployKSM" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obs.fullname" . }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: kube-state-metrics
{{- end }}
