customer: div-ya-argo
environment: div-ya-argo
project: countly-customers
server: https://35.193.84.128
gcpServiceAccountEmail: gcr-argo@countly-01.iam.gserviceaccount.com
secretManagerProjectID: countly-tools
clusterProjectID: countly-dev-313620
clusterName: div-ya-argo
clusterLocation: us-central1-a
hostname: div-ya-argo.count.ly
sizing: tier1
security: open
tls: letsencrypt
observability: disabled
kafkaConnect: balanced
migration: disabled
