customer: gcr-argo
environment: gcr-argo
project: countly-customers
server: https://34.123.21.39
gcpServiceAccountEmail: gcr-argo@countly-01.iam.gserviceaccount.com
secretManagerProjectID: countly-tools
clusterProjectID: countly-dev-313620
clusterName: gcr-argo
clusterLocation: us-central1-a
hostname: gcr-argo.count.ly
sizing: tier1
security: open
tls: letsencrypt
observability: disabled
kafkaConnect: balanced
migration: disabled
