customer: helm-argo-test
environment: helm-argo-test
project: countly-customers
server: https://34.60.110.103
sizing: tier1
security: open
tls: letsencrypt
observability: disabled
kafkaConnect: balanced
secretBackend: direct
