customer: tls-argo
environment: tls-argo
project: countly-customers
server: https://34.70.85.2
gcpServiceAccountEmail: gcr-argo@countly-01.iam.gserviceaccount.com
secretManagerProjectID: countly-tools
clusterProjectID: countly-dev-313620
clusterName: tls-argo
clusterLocation: us-central1-a
hostname: tls-argo.count.ly
sizing: tier1
security: open
tls: provided
observability: disabled
kafkaConnect: balanced
migration: disabled
