{{- if or (include "obs.deployAlloy" .) (include "obs.deployAlloyMetrics" .) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "obs.fullname" . }}-alloy
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: alloy
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups: ["metrics.k8s.io"]
  resources:
  - nodes
  - pods
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "obs.fullname" . }}-alloy
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: alloy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "obs.fullname" . }}-alloy
subjects:
- kind: ServiceAccount
  name: {{ include "obs.fullname" . }}-alloy
  namespace: {{ .Release.Namespace }}
{{- end }}
