{{- if (include "obs.deployAlloy" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "obs.fullname" . }}-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: alloy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "obs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alloy
  ports:
  - name: http-metrics
    port: 12345
    targetPort: 12345
    protocol: TCP
{{- end }}
