{{- if or (include "obs.deployAlloy" .) (include "obs.deployAlloyMetrics" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "obs.fullname" . }}-alloy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: alloy
{{- end }}
