{{- if (include "obs.deployTempo" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "obs.fullname" . }}-tempo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "obs.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "obs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: tempo
  ports:
  - name: http
    port: 3200
    targetPort: 3200
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: 9095
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
{{- end }}
