{{- if .Values.podDisruptionBudget.keeper.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "countly-clickhouse.fullname" . }}-keeper-pdb
  labels:
    {{- include "countly-clickhouse.labels" . | nindent 4 }}
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-clickhouse.syncWave" (dict "wave" "3" "root" .) | nindent 4 }}
  {{- end }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.keeper.maxUnavailable | default 1 }}
  selector:
    matchLabels:
      clickhouse.com/role: clickhouse-keeper
{{- end }}
