{{- if (.Values.server.settings.prometheus).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "countly-clickhouse.fullname" . }}-server-metrics
  labels:
    {{- include "countly-clickhouse.labels" . | nindent 4 }}
    countly.io/component: clickhouse-server
    countly.io/metrics: "true"
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-clickhouse.syncWave" (dict "wave" "10" "root" .) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if eq (.Values.serviceMonitor.serviceType | default "headless") "headless" }}
  clusterIP: None
  {{- end }}
  selector:
    clickhouse.com/role: clickhouse-server
  ports:
    - name: metrics
      port: {{ (.Values.server.settings.prometheus).port | default 9363 }}
      targetPort: {{ (.Values.server.settings.prometheus).port | default 9363 }}
      protocol: TCP
{{- end }}
---
{{- if (.Values.keeper.settings.prometheus).enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "countly-clickhouse.fullname" . }}-keeper-metrics
  labels:
    {{- include "countly-clickhouse.labels" . | nindent 4 }}
    countly.io/component: clickhouse-keeper
    countly.io/metrics: "true"
  {{- if .Values.argocd.enabled }}
  annotations:
    {{- include "countly-clickhouse.syncWave" (dict "wave" "10" "root" .) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  {{- if eq (.Values.serviceMonitor.serviceType | default "headless") "headless" }}
  clusterIP: None
  {{- end }}
  selector:
    clickhouse.com/role: clickhouse-keeper
  ports:
    - name: metrics
      port: {{ (.Values.keeper.settings.prometheus).port | default 9090 }}
      targetPort: {{ (.Values.keeper.settings.prometheus).port | default 9090 }}
      protocol: TCP
{{- end }}
