global:
  clusterProfile: production

# --- Network Policy ---
networkPolicy:
  enabled: true

# --- countly chart overrides ---
api:
  replicaCount: 2
  resources:
    requests: { cpu: "1", memory: "3.5Gi" }
    limits: { cpu: "1", memory: "4Gi" }
  hpa:
    minReplicas: 2
    maxReplicas: 6
  pdb:
    enabled: true
    minAvailable: 1
  scheduling:
    antiAffinity:
      enabled: true
      type: preferred

frontend:
  replicaCount: 2
  resources:
    requests: { cpu: "1", memory: "2.5Gi" }
    limits: { cpu: "1", memory: "3Gi" }
  hpa:
    minReplicas: 2
    maxReplicas: 4
  pdb:
    enabled: true
    minAvailable: 1

ingestor:
  replicaCount: 2
  resources:
    requests: { cpu: "1", memory: "3Gi" }
    limits: { cpu: "1", memory: "3Gi" }
  hpa:
    minReplicas: 2
    maxReplicas: 12
  pdb:
    enabled: true
    minAvailable: 1

aggregator:
  replicaCount: 4
  resources:
    requests: { cpu: "1", memory: "3.5Gi" }
    limits: { cpu: "2", memory: "4Gi" }
  hpa:
    minReplicas: 4
    maxReplicas: 8
  pdb:
    enabled: true
    minAvailable: 1

jobserver:
  replicaCount: 1
  resources:
    requests: { cpu: "1", memory: "3Gi" }
    limits: { cpu: "1", memory: "3Gi" }

# --- countly-mongodb overrides ---
mongodb:
  members: 3
  resources:
    requests: { cpu: "3", memory: "6Gi" }
    limits: { cpu: "4", memory: "8Gi" }
  persistence:
    size: 500Gi

# --- countly-clickhouse overrides ---
shards: 1
replicas: 2

server:
  resources:
    requests: { cpu: "4", memory: "12Gi" }
    limits: { cpu: "4", memory: "16Gi" }
  persistence:
    size: 500Gi
  scheduling:
    antiAffinity:
      enabled: true

keeper:
  replicas: 3
  resources:
    requests: { cpu: "500m", memory: "1Gi" }
    limits: { cpu: "1", memory: "2Gi" }
  persistence:
    size: 50Gi

podDisruptionBudget:
  server:
    enabled: true
    maxUnavailable: 1
  keeper:
    enabled: true
    maxUnavailable: 1

# --- countly-kafka overrides ---
brokers:
  replicas: 3
  resources:
    requests: { cpu: "2", memory: "12Gi" }
    limits: { cpu: "2", memory: "12Gi" }
  jvmOptions:
    xms: "4g"
    xmx: "4g"
  persistence:
    volumes:
      - id: 0
        size: 200Gi
  config:
    default.replication.factor: 2
    min.insync.replicas: 2
    auto.create.topics.enable: false
  scheduling:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule

controllers:
  replicas: 3
  resources:
    requests: { cpu: "500m", memory: "2Gi" }
    limits: { cpu: "1", memory: "2Gi" }
  scheduling:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule

cruiseControl:
  enabled: true
  resources:
    requests: { cpu: "1", memory: "2Gi" }
    limits: { cpu: "1", memory: "2Gi" }

kafkaConnect:
  replicas: 2
  resources:
    requests: { cpu: "2", memory: "8Gi" }
    limits: { cpu: "2", memory: "8Gi" }
  jvmOptions:
    xms: "5g"
    xmx: "5g"
